"""phrase clustering

Revision ID: 3121b3c34e10
Revises: 3bb06ccd6e22
Create Date: 2026-09-07 13:00:16.883523

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3121b3c34e10"
down_revision: str | Sequence[str] | None = "3bb06ccd6e22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "phrase_embeddings",
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("phrase", sa.Text(), nullable=False),
        sa.Column("vector", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_table(
        "phrase_clusters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("posting_id", sa.BigInteger(), nullable=False),
        sa.Column("clusters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("posting_id", name="uq_phrase_clusters_posting"),
    )
    op.create_index(
        op.f("ix_phrase_clusters_posting_id"),
        "phrase_clusters",
        ["posting_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_phrase_clusters_posting_id"), table_name="phrase_clusters")
    op.drop_table("phrase_clusters")
    op.drop_table("phrase_embeddings")
    # ### end Alembic commands ###
