"""ats board tracking and posting company slug

Revision ID: 323bfe5d9a3b
Revises: 1e060791e589
Create Date: 2026-09-05 05:44:52.580682

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "323bfe5d9a3b"
down_revision: str | Sequence[str] | None = "1e060791e589"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ats_boards",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("company_slug", sa.String(length=255), nullable=False),
        sa.Column("etag", sa.String(length=255), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "company_slug", name="uq_ats_boards_source_slug"),
    )
    op.add_column(
        "job_postings", sa.Column("company_slug", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_postings", "company_slug")
    op.drop_table("ats_boards")
    # ### end Alembic commands ###
