"""tracked boards group

Revision ID: 3bb06ccd6e22
Revises: 4b7a97ce2ef6
Create Date: 2026-09-07 09:46:09.070293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "3bb06ccd6e22"
down_revision: str | Sequence[str] | None = "4b7a97ce2ef6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracked_boards", sa.Column("group", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tracked_boards", "group")
    # ### end Alembic commands ###
