"""refresh token families

Revision ID: 7cac70ddda03
Revises: 8ebed69896a7
Create Date: 2026-09-04 01:29:03.810264

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7cac70ddda03"
down_revision: str | Sequence[str] | None = "8ebed69896a7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token_families",
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("family_id"),
    )
    op.create_index(
        op.f("ix_refresh_token_families_subject"),
        "refresh_token_families",
        ["subject"],
        unique=False,
    )
    op.create_table(
        "refresh_token_index",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("family_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"], ["refresh_token_families.family_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("token_hash"),
    )
    op.create_index(
        op.f("ix_refresh_token_index_family_id"),
        "refresh_token_index",
        ["family_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_refresh_token_index_family_id"), table_name="refresh_token_index"
    )
    op.drop_table("refresh_token_index")
    op.drop_index(
        op.f("ix_refresh_token_families_subject"), table_name="refresh_token_families"
    )
    op.drop_table("refresh_token_families")
    # ### end Alembic commands ###
