"""revisions table

Revision ID: 8ebed69896a7
Revises: b048f4a5b24c
Create Date: 2026-09-03 16:54:54.220499

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "8ebed69896a7"
down_revision: str | Sequence[str] | None = "b048f4a5b24c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revisions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("jd_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "tailored_cv", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("promoted", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revisions_name"), "revisions", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_revisions_name"), table_name="revisions")
    op.drop_table("revisions")
    # ### end Alembic commands ###
