"""job postings and gap analyses

Revision ID: b040afb81ac3
Revises: 7cac70ddda03
Create Date: 2026-09-05 01:14:33.292559

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "b040afb81ac3"
down_revision: str | Sequence[str] | None = "7cac70ddda03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_postings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("jd_text", sa.Text(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_job_postings_source_ext"),
    )
    op.create_index(
        "ix_job_postings_content_hash", "job_postings", ["content_hash"], unique=False
    )
    op.create_table(
        "jd_analyses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("posting_id", sa.BigInteger(), nullable=False),
        sa.Column("analyzer_version", sa.String(length=32), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["posting_id"], ["job_postings.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "posting_id", "analyzer_version", name="uq_jd_analyses_posting_version"
        ),
    )
    op.create_index(
        op.f("ix_jd_analyses_analyzer_version"),
        "jd_analyses",
        ["analyzer_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_jd_analyses_posting_id"), "jd_analyses", ["posting_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_jd_analyses_posting_id"), table_name="jd_analyses")
    op.drop_index(op.f("ix_jd_analyses_analyzer_version"), table_name="jd_analyses")
    op.drop_table("jd_analyses")
    op.drop_index("ix_job_postings_content_hash", table_name="job_postings")
    op.drop_table("job_postings")
    # ### end Alembic commands ###
